import type { FuelFormData, FuelRecord } from './types';

export const FUEL_STORAGE_KEY = 'henrique-transportes:fuel-records';

export const DRIVER_OPTIONS = [
  'Patrick',
  'Anderson',
  'Carlos',
  'Eduardo',
  'João',
  'Marcelo',
] as const;

export const INITIAL_FUEL_FORM: FuelFormData = {
  station: '',
  plate: '',
  date: new Date().toISOString().slice(0, 10),
  km: '',
  dieselLiters: '',
  dieselTotalValue: '',
  hasArla: false,
  arlaLiters: '',
  arlaTotalValue: '',
  driver: '',
};

export const INITIAL_FUEL_RECORDS: FuelRecord[] = [
  {
    id: 'fuel-001',
    date: '2026-05-04',
    station: 'MIME',
    plate: 'SKT8H52',
    km: 144176,
    dieselLiters: 466,
    dieselTotalValue: 2539.7,
    arlaLiters: 0,
    arlaTotalValue: 0,
    driver: 'Patrick',
    status: 'F',
  },
  {
    id: 'fuel-002',
    date: '2026-05-07',
    station: 'MIME',
    plate: 'SKT8H52',
    km: 145659,
    dieselLiters: 395,
    dieselTotalValue: 2152.75,
    arlaLiters: 0,
    arlaTotalValue: 0,
    driver: 'Patrick',
    status: 'F',
  },
  {
    id: 'fuel-003',
    date: '2026-05-10',
    station: 'MIME',
    plate: 'SKT8H52',
    km: 146817,
    dieselLiters: 415,
    dieselTotalValue: 2261.75,
    arlaLiters: 0,
    arlaTotalValue: 0,
    driver: 'Patrick',
    status: 'F',
  },
  {
    id: 'fuel-004',
    date: '2026-05-14',
    station: 'MIME',
    plate: 'SKT8H52',
    km: 148496,
    dieselLiters: 400,
    dieselTotalValue: 2180,
    arlaLiters: 20,
    arlaTotalValue: 109.2,
    driver: 'Patrick',
    status: 'N',
  },
  {
    id: 'fuel-005',
    date: '2026-05-18',
    station: 'MIME',
    plate: 'SKT8H52',
    km: 150277,
    dieselLiters: 400,
    dieselTotalValue: 2180,
    arlaLiters: 0,
    arlaTotalValue: 0,
    driver: 'Patrick',
    status: 'F',
  },
  {
    id: 'fuel-006',
    date: '2026-05-24',
    station: 'MIME',
    plate: 'SKT8H52',
    km: 153712,
    dieselLiters: 350,
    dieselTotalValue: 1907.5,
    arlaLiters: 0,
    arlaTotalValue: 0,
    driver: 'Patrick',
    status: 'N',
  },
  {
    id: 'fuel-007',
    date: '2026-05-28',
    station: 'MIME',
    plate: 'SKT8H52',
    km: 155871,
    dieselLiters: 400,
    dieselTotalValue: 2168,
    arlaLiters: 40,
    arlaTotalValue: 216.8,
    driver: 'Patrick',
    status: 'N',
  },
];
