import {
  BarChart3,
  ClipboardList,
  Fuel,
  Landmark,
  LayoutDashboard,
  Link2,
  Map,
  NotebookPen,
  ShieldCheck,
  Truck,
  Users,
  Building2,
  CalendarDays,
  Wrench,
} from 'lucide-react';

import type { NavigationItem } from './types';

export const APP_NAVIGATION_ITEMS: NavigationItem[] = [
  {
    id: 'overview',
    label: 'Dashboard',
    icon: LayoutDashboard,
    path: '/dashboard',
    permission: 'dashboard',
  },
  {
    id: 'bi',
    label: 'BI Operacional',
    icon: BarChart3,
    path: '/bi',
    permission: 'bi',
  },
  {
    id: 'registrations',
    label: 'Cadastros',
    icon: ClipboardList,
    children: [
      {
        id: 'vehicles',
        label: 'Veículos',
        icon: Truck,
        path: '/cadastros/veiculos',
        permission: 'registrations.vehicles',
      },
      {
        id: 'employees',
        label: 'Colaboradores',
        icon: Users,
        path: '/cadastros/colaboradores',
        permission: 'registrations.employees',
      },
      {
        id: 'shippers',
        label: 'Embarcadores',
        icon: Building2,
        path: '/cadastros/embarcadores',
        permission: 'registrations.shippers',
      },
      {
        id: 'company-profile',
        label: 'Empresa',
        icon: Landmark,
        path: '/cadastros/empresa',
        permission: 'registrations.company',
      },
    ],
  },
  {
    id: 'fuel',
    label: 'Combustível',
    icon: Fuel,
    path: '/fuel',
    permission: 'fuel',
  },
  {
    id: 'travel',
    label: 'Viagens',
    icon: Map,
    path: '/travel',
    permission: 'travel',
  },

  {
    id: 'vehicle-sets',
    label: 'Conjuntos',
    icon: Link2,
    path: '/conjuntos',
    permission: 'vehicle_sets',
  },
  {
    id: 'acertos',
    label: 'Acertos',
    icon: NotebookPen,
    path: '/acertos',
    permission: 'settlements',
  },
  {
    id: 'finance',
    label: 'Financeiro',
    icon: Landmark,
    path: '/finance',
    permission: 'finance',
  },
  {
    id: 'maintenance',
    label: 'Manutenção',
    icon: Wrench,
    path: '/maintenance',
    permission: 'maintenance',
  },
  {
    id: 'security',
    label: 'Segurança',
    icon: ShieldCheck,
    path: '/admin/seguranca',
    permission: 'admin.security',
    roles: ['Administrador'],
  },
  {
    id: 'logistic',
    label: 'Logística',
    icon: Truck,
    permission: 'logistics',
    children: [
      {
        id: 'logistic-panel',
        label: 'Painel',
        icon: ClipboardList,
        path: '/logistic',
        permission: 'logistics',
      },
      {
        id: 'logistic-calendar',
        label: 'Calendário de cargas',
        icon: CalendarDays,
        path: '/logistic/calendar',
        permission: 'logistics',
      },
    ],
  },
];
